critiquebrainz/frontend/log/forms.py
from flask_wtf import Form
from flask_babel import gettext
from wtforms import TextAreaField, validators


class AdminActionForm(Form):
    reason = TextAreaField(validators=[
        validators.DataRequired(message=gettext("You need to sepicify a reason for taking this action."))
    ])

critiquebrainz/frontend/profile/applications/forms.py
from flask_wtf import Form
from flask_babel import gettext
from wtforms import StringField, validators


class ApplicationForm(Form):
    name = StringField(gettext('Application name'), [
        validators.DataRequired(message=gettext("Application name field is empty.")),
        validators.Length(min=3, message=gettext("Application name needs to be at least 3 characters long.")),
        validators.Length(max=64, message=gettext("Application name needs to be at most 64 characters long."))])
    desc = StringField(gettext('Description'), [
        validators.DataRequired(message=gettext("Client description field is empty.")),
        validators.Length(min=3, message=gettext("Client description needs to be at least 3 characters long.")),
        validators.Length(max=512, message=gettext("Client description needs to be at most 512 characters long."))])
    website = StringField(gettext('Homepage'), [
        validators.DataRequired(message=gettext("Homepage field is empty.")),
        validators.URL(message=gettext("Homepage is not a valid URI."))])
    redirect_uri = StringField(gettext('Authorization callback URL'), [
        validators.DataRequired(message=gettext("Authorization callback URL field is empty.")),
        validators.URL(message=gettext("Authorization callback URL is invalid."))])

critiquebrainz/frontend/profile/forms.py
from flask_wtf import Form
from flask_babel import gettext
from wtforms import StringField, BooleanField, validators
from wtforms.fields.html5 import EmailField


class ProfileEditForm(Form):
    display_name = StringField(gettext("Display name"), [
        validators.DataRequired(message=gettext("Display name field is empty.")),
        validators.Length(min=3, message=gettext("Display name needs to be at least 3 characters long.")),
        validators.Length(max=64, message=gettext("Display name needs to be at most 64 characters long."))])
    email = EmailField(gettext("Email"), [
        validators.Optional(strip_whitespace=False),
        validators.Email(message=gettext("Email field is not a valid email address."))])
    show_gravatar = BooleanField(gettext("Show my Gravatar"))

critiquebrainz/frontend/__init__.py
from flask import Flask
import os


def create_app(debug=None):
    app = Flask(__name__)

    # Configuration files
    import critiquebrainz.default_config
    app.config.from_object(critiquebrainz.default_config)
    app.config.from_pyfile(os.path.join(
        os.path.dirname(os.path.realpath(__file__)),
        "..", "config.py"
    ), silent=True)
    if debug is not None:
        app.debug = debug

    # Error handling
    from critiquebrainz.frontend.errors import init_error_handlers
    init_error_handlers(app)

    # Logging
    from critiquebrainz import loggers
    loggers.init_loggers(app)

    if app.debug:
        # Debug toolbar
        from flask_debugtoolbar import DebugToolbarExtension
        DebugToolbarExtension(app)
        app.config['DEBUG_TB_TEMPLATE_EDITOR_ENABLED'] = True

    from flask_uuid import FlaskUUID
    FlaskUUID(app)

    from critiquebrainz.data import db
    db.init_app(app)

    # Memcached
    if 'MEMCACHED_SERVERS' in app.config:
        from critiquebrainz import cache
        cache.init(app.config['MEMCACHED_SERVERS'],
                   app.config['MEMCACHED_NAMESPACE'],
                   debug=1 if app.debug else 0)

    import critiquebrainz.frontend.babel
    babel.init_app(app)

    import critiquebrainz.frontend.login
    login.login_manager.init_app(app)
    from critiquebrainz.frontend.login.provider import MusicBrainzAuthentication
    login.mb_auth = MusicBrainzAuthentication(
        name='musicbrainz',
        client_id=app.config['MUSICBRAINZ_CLIENT_ID'],
        client_secret=app.config['MUSICBRAINZ_CLIENT_SECRET'],
        authorize_url="https://musicbrainz.org/oauth2/authorize",
        access_token_url="https://musicbrainz.org/oauth2/token",
        base_url="https://musicbrainz.org/")

    # APIs
    from critiquebrainz.frontend.apis import mbspotify
    mbspotify.init(app.config['MBSPOTIFY_BASE_URI'], app.config['MBSPOTIFY_ACCESS_KEY'])
    from critiquebrainz.frontend.apis import musicbrainz
    musicbrainz.init(app.config['MUSICBRAINZ_USERAGENT'], critiquebrainz.__version__,
                     hostname=app.config['MUSICBRAINZ_HOSTNAME'])

    # Template utilities
    app.jinja_env.add_extension('jinja2.ext.do')
    from critiquebrainz.utils import reformat_date, reformat_datetime, track_length
    app.jinja_env.filters['date'] = reformat_date
    app.jinja_env.filters['datetime'] = reformat_datetime
    app.jinja_env.filters['track_length'] = track_length
    app.jinja_env.filters['entity_details'] = musicbrainz.get_entity_by_id

    # Blueprints
    from critiquebrainz.frontend.views import frontend_bp
    from critiquebrainz.frontend.review.views import review_bp
    from critiquebrainz.frontend.search.views import search_bp
    from critiquebrainz.frontend.artist.views import artist_bp
    from critiquebrainz.frontend.release_group.views import release_group_bp
    from critiquebrainz.frontend.event.views import event_bp
    from critiquebrainz.frontend.mapping.views import mapping_bp
    from critiquebrainz.frontend.user.views import user_bp
    from critiquebrainz.frontend.profile.views import profile_bp
    from critiquebrainz.frontend.profile.applications.views import profile_apps_bp
    from critiquebrainz.frontend.login.views import login_bp
    from critiquebrainz.frontend.oauth.views import oauth_bp
    from critiquebrainz.frontend.reports.views import reports_bp
    from critiquebrainz.frontend.log.views import log_bp

    app.register_blueprint(frontend_bp)
    app.register_blueprint(review_bp, url_prefix='/review')
    app.register_blueprint(search_bp, url_prefix='/search')
    app.register_blueprint(artist_bp, url_prefix='/artist')
    app.register_blueprint(release_group_bp, url_prefix='/release-group')
    app.register_blueprint(event_bp, url_prefix='/event')
    app.register_blueprint(mapping_bp, url_prefix='/mapping')
    app.register_blueprint(user_bp, url_prefix='/user')
    app.register_blueprint(profile_bp, url_prefix='/profile')
    app.register_blueprint(profile_apps_bp, url_prefix='/profile/applications')
    app.register_blueprint(login_bp, url_prefix='/login')
    app.register_blueprint(oauth_bp, url_prefix='/oauth')
    app.register_blueprint(reports_bp, url_prefix='/reports')
    app.register_blueprint(log_bp, url_prefix='/log')

    return app

critiquebrainz/frontend/apis/__init__.py
"""
This package (api) provides modules to access external services:
 - MusicBrainz (with advanced relationship support)
 - Spotify
 - mbspotify

See documentation in each module for information about usage.
"""

critiquebrainz/frontend/artist/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_babel import gettext
from werkzeug.exceptions import BadRequest, NotFound
from critiquebrainz.frontend.apis import musicbrainz
from critiquebrainz.data.model.review import Review

artist_bp = Blueprint('artist', __name__)


@artist_bp.route('/<uuid:id>')
def entity(id):
    """Artist page.

    Displays release groups (split up into several sections depending on their
    type), artist information (type, members/member of, external links).
    """
    artist = musicbrainz.get_artist_by_id(id)
    if not artist:
        raise NotFound(gettext("Sorry, we couldn't find an artist with that MusicBrainz ID."))

    # Preparing artist-rels
    if 'band-members' in artist:
        artist['current_members'] = []
        artist['former_members'] = []
        for member in artist['band-members']:
            if 'ended' in member and member['ended'] == 'true':
                artist['former_members'].append(member)
            else:
                artist['current_members'].append(member)


    release_type = request.args.get('release_type', default='album')
    if release_type not in ['album', 'single', 'ep', 'broadcast', 'other']:  # supported release types
        raise BadRequest("Unsupported release type.")

    page = int(request.args.get('page', default=1))
    if page < 1:
        return redirect(url_for('.reviews'))
    limit = 20
    offset = (page - 1) * limit
    count, release_groups = musicbrainz.browse_release_groups(artist_id=id, release_types=[release_type],
                                                              limit=limit, offset=offset)
    for release_group in release_groups:
        # TODO(roman): Count reviews instead of fetching them.
        reviews, review_count = Review.list(entity_id=release_group['id'], entity_type='release_group', sort='created', limit=1)
        release_group['review_count'] = review_count
    return render_template('artist.html', id=id, artist=artist, release_type=release_type,
                           release_groups=release_groups, page=page, limit=limit, count=count)

critiquebrainz/frontend/event/views.py
from itertools import groupby
from operator import itemgetter
from flask import Blueprint, render_template, request
from flask_login import current_user
from flask_babel import gettext
from critiquebrainz.frontend.apis import musicbrainz
from critiquebrainz.data.model.review import Review
from werkzeug.exceptions import NotFound


event_bp = Blueprint('event', __name__)


@event_bp.route('/<uuid:id>')
def entity(id):
    id = str(id)
    event = musicbrainz.get_event_by_id(id)
    if not event:
        raise NotFound(gettext("Sorry, we couldn't find a event with that MusicBrainz ID."))

    if 'artist-relation-list' in event and event['artist-relation-list']:
        artists_sorted = sorted(event['artist-relation-list'], key=itemgetter('type'))
        event['artists_grouped'] = groupby(artists_sorted, itemgetter('type'))

    if current_user.is_authenticated():
        my_reviews, my_count = Review.list(entity_id=id, entity_type='event', user_id=current_user.id)
        if my_count != 0:
            my_review = my_reviews[0]
        else:
            my_review = None
    else:
        my_review = None

    limit = int(request.args.get('limit', default=10))
    offset = int(request.args.get('offset', default=0))
    reviews, count = Review.list(entity_id=id, entity_type='event', sort='rating', limit=limit, offset=offset)

    return render_template('event.html', id=id, event=event, reviews=reviews,
                           my_review=my_review, limit=limit, offset=offset, count=count)

critiquebrainz/frontend/log/views.py
from itertools import groupby
from flask import Blueprint, render_template, flash, request, jsonify
from flask_babel import gettext
from critiquebrainz.data.model.moderation_log import ModerationLog

log_bp = Blueprint('log', __name__)

RESULTS_LIMIT = 20


@log_bp.route('/')
def browse():
    results, count = ModerationLog.list(limit=RESULTS_LIMIT)

    if not results:
        flash(gettext("No logs to display."), "warning")

    results = groupby(results, lambda log: log.timestamp.strftime('%d %b, %G'))

    return render_template('log/log.html', count=count, results=results, limit=RESULTS_LIMIT)


@log_bp.route('/more')
def more():
    page = int(request.args.get('page', default=0))
    offset = page * RESULTS_LIMIT

    results, count = ModerationLog.list(offset=offset, limit=RESULTS_LIMIT)
    results = groupby(results, lambda log: log.timestamp.strftime('%d %b, %G'))

    template = render_template('log/log_results.html', results=results)
    return jsonify(results=template, more=(count-offset-RESULTS_LIMIT) > 0)

critiquebrainz/frontend/login/__init__.py
"""
Package login provides authentication functionality for CritiqueBrainz.

It is based on OAuth2 protocol. MusicBrainz is the only supported provider.
"""
from flask import redirect, url_for
from flask_login import LoginManager, current_user
from flask_babel import gettext
from critiquebrainz.data.model.user import User
from critiquebrainz.data.model.mixins import AnonymousUser
from werkzeug.exceptions import Unauthorized
from functools import wraps

mb_auth = None

login_manager = LoginManager()
login_manager.login_view = 'login.index'
login_manager.login_message = gettext(u"Please sign in to access this page.")
login_manager.localize_callback = gettext
login_manager.anonymous_user = AnonymousUser


@login_manager.user_loader
def load_user(user_id):
    return User.get(id=user_id)


def login_forbidden(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if current_user.is_anonymous() is False:
            return redirect(url_for('frontend.index'))
        return f(*args, **kwargs)

    return decorated


def admin_view(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if not current_user.is_admin():
            raise Unauthorized(gettext('You must be an administrator to view this page.'))
        return f(*args, **kwargs)

    return decorated

critiquebrainz/frontend/login/views.py
from flask import Blueprint, request, redirect, render_template, url_for, session, flash
from flask_login import login_user, logout_user, login_required
from flask_babel import gettext
from critiquebrainz.frontend.login import mb_auth, login_forbidden

login_bp = Blueprint('login', __name__)


@login_bp.route('/')
@login_forbidden
def index():
    return render_template('login/login.html')


@login_bp.route('/musicbrainz')
@login_forbidden
def musicbrainz():
    session['next'] = request.args.get('next')
    return redirect(mb_auth.get_authentication_uri())


@login_bp.route('/musicbrainz/post')
@login_forbidden
def musicbrainz_post():
    """Callback endpoint."""
    if mb_auth.validate_post_login():
        login_user(mb_auth.get_user())
        next = session.get('next')
        if next:
            return redirect(next)
    else:
        flash(gettext("Login failed."), 'error')
    return redirect(url_for('frontend.index'))


@login_bp.route('/logout')
@login_required
def logout():
    logout_user()
    session.clear()
    return redirect(url_for('frontend.index'))

critiquebrainz/frontend/mapping/__init__.py
"""
Package mapping is basically an interface for mbspotify project.

It allows users to create mappings between release groups and albums on
Spotify. These mappings are then used to show embedded Spotify player on some
pages. See https://github.com/metabrainz/mbspotify for more info about this
project.
"""

critiquebrainz/frontend/oauth/views.py
from flask import Blueprint, render_template, redirect, request
from flask_login import login_required, current_user

from critiquebrainz.utils import build_url
from critiquebrainz.ws.oauth import oauth
from critiquebrainz.data.model.oauth_client import OAuthClient

oauth_bp = Blueprint('oauth', __name__)


@oauth_bp.route('/authorize', methods=['GET', 'POST'])
@login_required
def authorize_prompt():
    """OAuth 2.0 authorization endpoint."""
    response_type = request.args.get('response_type')
    client_id = request.args.get('client_id')
    redirect_uri = request.args.get('redirect_uri')
    scope = request.args.get('scope')
    state = request.args.get('state')

    if request.method == 'GET':  # Client requests access
        oauth.validate_authorization_request(client_id, response_type, redirect_uri, scope)
        client = OAuthClient.query.get(client_id)
        return render_template('oauth/prompt.html', client=client, scope=scope,
                               cancel_url=build_url(redirect_uri, dict(error='access_denied')))

    if request.method == 'POST':  # User grants access to the client
        oauth.validate_authorization_request(client_id, response_type, redirect_uri, scope)
        code = oauth.generate_grant(client_id, current_user.id, redirect_uri, scope)
        return redirect(build_url(redirect_uri, dict(code=code, state=state)))

critiquebrainz/frontend/templates/search/index.html
{% extends 'base.html' %}

{% block title %}
{% if request.args.get('query', default=False) %}
  {{ _('Search results') }}
{% else %}
  {{ _('Search') }}
{% endif %}
- CritiqueBrainz
{% endblock %}

{% block content %}
<h3>{{ _('Search') }}</h3>

<form method="GET" class="form-horizontal" role="form">
  <div class="form-group">
    <label for="input-query" class="col-sm-2 control-label">{{ _('Query') }}</label>
    <div class="col-sm-3">
      <input id="input-query" name="query" class="form-control" value="{{ request.args.get('query', default='') }}">
    </div>
  </div>
  <div class="form-group">
    <label for="type-selector" class="col-sm-2 control-label">{{ _('Type') }}</label>
    <div class="col-sm-2">
      <select id="type-selector" name="type" class="form-control">
        <option value="artist" {% if type=="artist" %}selected="selected"{% endif %}>{{ _('Artist') }}</option>
        <option value="release-group" {% if type=="release-group" %}selected="selected"{% endif %}>{{ _('Release group') }}</option>
        <option value="event" {% if type=="event" %}selected="selected"{% endif %}>{{ _('Event') }}</option>
      </select>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">{{ _('Search') }}</button>
    </div>
  </div>
</form>

{% if request.args.get('query', default=False) %}
  <hr />
  {% if not results %}
    <p class="lead" style="text-align: center;">{{ _('No results found') }}</p>
  {% else %}

    <table class="table table-hover">
      <thead>
      {% if type=="artist" %}
        <tr>
          <th>{{ _('Name') }}</th>
          <th>{{ _('Sort name') }}</th>
          <th>{{ _('Type') }}</th>
          <th>{{ _('Country') }}</th>
        </tr>
      {% elif type=="event" %}
        <tr>
          <th>{{ _('Name') }}</th>
          <th>{{ _('Artist') }}</th>
          <th>{{ _('Location') }}</th>
        </tr>
      {% elif type=="release-group" %}
        <tr>
          <th>{{ _('Release group') }}</th>
          <th>{{ _('Artist') }}</th>
          <th>{{ _('Type') }}</th>
        </tr>
      {% endif %}
      </thead>
      <tbody id="results">{% include 'search/results.html' %}</tbody>
    </table>

    {% if count > limit %}
      <div>
      <button id="more-button" type="button" class="btn btn-primary" onclick="load_more();" >{{ _('Load more results') }}</button>
      <span id="loading-message" class="text-muted" style="display:none;">{{ _('Loading more results...') }}</span>
    </div>
    {% endif %}

  {% endif %}
{% endif %}
{% endblock %}

{% if count > limit %}
  {% block scripts %}
    {{ super() }}
    <script>
      var current_page = 0;
      function load_more() {
        var more_button = $("#more-button");
        var loading_message = $("#loading-message");
        more_button.hide();
        loading_message.show();
        $.ajax({
          url: "{{ url_for('search.more') }}",
          data: { query: "{{ query }}", type: "{{ type }}", page: ++current_page }
        })
            .done(function(data) {
              loading_message.hide();
              $("#results").append(data.results);
              if (data.more === true) more_button.show();
            })
            .fail(function() {
              alert({{ _('Failed to load more search results!') | tojson }});
            });
      }
    </script>
  {% endblock %}
{% endif %}

critiquebrainz/frontend/templates/search/results.html
{% for result in results %}

  {% if type=="artist" %}
    <tr>
      <td>
        <a href="{{ url_for('artist.entity', id=result.id) }}">{{ result['name'] }}</a>
        {% if result['disambiguation'] %}<span class="text-muted">({{ result['disambiguation'] }})</span>{% endif %}
      </td>
      <td>{{ result['sort-name'] }}</td>
      <td>{{ result['type'] or '-' }}</td>
      <td>{{ result['country'] or '-' }}</td>
    </tr>

  {% elif type=="release-group" %}
    <tr>
      <td>
        <a href="{{ url_for('release_group.entity', id=result.id) }}">{{ result['title'] }}</a>
        {% if result['disambiguation'] %}<span class="text-muted">({{ result['disambiguation'] }})</span>{% endif %}
      </td>
      <td><a href="{{ url_for('artist.entity', id=result['artist-credit'][0].artist.id) }}">{{ result['artist-credit-phrase'] }}</a></td>
      <td>{{ result['primary-type'] or '-' }}</td>
    </tr>

  {% elif type=="event" %}
    <tr>
      <td>
        <a href="{{ url_for('event.entity', id=result.id) }}">{{ result['name'] }}</a>
        {% if result['disambiguation'] %}<span class="text-muted">({{ result['life-span']['begin'] }} - {{ result['life-span']['end'] }})</span>{% endif %}
      </td>
      <td>
        {% if result['artist-relation-list'] %}
          <a href="{{ url_for('artist.entity', id=result['artist-relation-list'][0].artist.id) }}">{{ result['artist-relation-list'][0]['artist']['name'] or '-' }}</a>
          {% set count = result['artist-relation-list'] | length %}
          {% if count > 1 %}
            + {{ count - 1 }} {{ _("more") }}
          {% endif %}
        {% else %}
          -
        {% endif %}
      </td>
      <td>
        {% if result['place-relation-list'] %}
          {{ result['place-relation-list'][0]['place']['name'] or '-' }}
        {% else %}
          -
        {% endif %}
      </td>
    </tr>

  {% endif %}
{% endfor %}

critiquebrainz/frontend/templates/search/selector.html
{% extends 'base.html' %}

{% block title %}{{ _('Entity selection') }} - CritiqueBrainz{% endblock %}
{% set type = request.args.get('type', default='release-group') %}

{% block content %}
  <div id="content">
    <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
      <li {% if type=="release-group" %}class="active"{% endif %}>
        <a href="#release-group" data-toggle="tab">Release Group</a>
      </li>
      <li {% if type=="event" %}class="active"{% endif %}>
        <a href="#event" data-toggle="tab">Event</a>
      </li>
    </ul>

    <div class="tab-content">
      <div id="release-group" class="tab-pane {% if type=="release-group" %}active{% endif %}">
        <h3>{{ _('Release group selection') }}</h3>
        <form method="GET" class="form-horizontal" role="form">
          <div class="form-group">
            <label for="input-artist" class="col-sm-2 control-label">{{ _('Artist') }}</label>
            <div class="col-sm-4">
              <input id="input-artist" class="form-control" name="artist" type="text"
                     value="{{ request.args.get('artist', default='') }}">
            </div>
          </div>
          <div class="form-group">
            <label for="input-release-group" class="col-sm-2 control-label">{{ _('Release group') }}</label>
            <div class="col-sm-4">
              <input id="input-release-group" class="form-control" name="release_group" type="text"
                     value="{{ request.args.get('release_group', default='') }}">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-default">{{ _('Search') }}</button>
            </div>
          </div>
          <input type="hidden" name="next" value="{{ next }}" />
          <input type="hidden" name="type" value="release-group" />
        </form>
      </div>

      <div id="event" class="tab-pane {% if type=="event" %}active{% endif %}">
        <h3>{{ _('Event selection') }}</h3>
        <form method="GET" class="form-horizontal" role="form">
          <div class="form-group">
            <label for="input-release-group" class="col-sm-2 control-label">{{ _('Event') }}</label>
            <div class="col-sm-4">
              <input id="input-release-group" class="form-control" name="event" type="text"
                     value="{{ request.args.get('event', default='') }}">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-default">{{ _('Search') }}</button>
            </div>
          </div>
          <input type="hidden" name="next" value="{{ next }}" />
          <input type="hidden" name="type" value="event" />
        </form>
      </div>

    </div>
  </div>

{%
  if request.args.get('artist', default=False)
  or request.args.get('release_group', default=False)
  or request.args.get('event', default=False)
%}
  <hr />
  {% if not results %}
    <p class="lead" style="text-align: center;">{{ _('No results found') }}</p>
  {% else %}
    <form action="{{ next }}" method="GET">
      <table class="table table-hover">
        <thead>
        {% if type == "release-group" %}
          <tr>
            <th>{{ _('Artist') }}</th>
            <th>{{ _('Release group') }}</th>
            <th>{{ _('Type') }}</th>
            <th></th>
          </tr>
        {% elif type == "event"  %}
          <tr>
            <th>{{ _('Name') }}</th>
            <th>{{ _('Artist') }}</th>
            <th>{{ _('Location') }}</th>
            <th></th>
          </tr>
        {% endif %}
        </thead>
        <tbody id="results">{% include 'search/selector_results.html' %}</tbody>
      </table>

      <div class="row">
        {% if count > limit %}
          <div class="col-md-6">
            <button id="more-button" type="button" class="btn btn-default" onclick="load_more();" >{{ _('Load more results') }}</button>
            <span id="loading-message" class="text-muted" style="display:none;">{{ _('Loading more results...') }}</span>
          </div>
        {% endif %}
        <div class="col-md-6 form-actions">
          <button type="submit" class="pull-right btn btn-primary">{{ _('Continue') }}</button>
        </div>
      </div>
    </form>
  {% endif %}
{% endif %}
{% endblock %}

{% if count > limit %}
  {% block scripts %}
    {{ super() }}
    <script>
      var current_page = 0;
      function load_more() {
        var more_button = $("#more-button");
        var loading_message = $("#loading-message");
        more_button.hide();
        loading_message.show();
        $.ajax({
          url: "{{ url_for('search.selector_more') }}",
          data: {
            artist: "{{ artist }}",
            release_group: "{{ release_group }}",
            event: "{{ event }}",
            type: "{{ type }}",
            page: ++current_page
          }
        })
        .done(function(data) {
          loading_message.hide();
          $("#results").append(data.results);
          if (data.more === true) more_button.show();
        })
        .fail(function() {
          alert({{ _('Failed to load more search results!') | tojson }});
        });
      }
    </script>
  {% endblock %}
{% endif %}

critiquebrainz/frontend/templates/search/selector_results.html
{% for result in results %}

{% if type=="release-group" %}
  <tr>
    <td><a href="{{ url_for('artist.entity', id=result['artist-credit'][0].artist.id) }}" target="_blank">{{ result['artist-credit-phrase'] }}</a></td>
    <td>
      <a href="{{ url_for('release_group.entity', id=result.id) }}" target="_blank">{{ result['title'] }}</a>
      {% if result['disambiguation'] %}<span class="text-muted">({{ result['disambiguation'] }})</span>{% endif %}
    </td>
    <td>{{ result['primary-type'] or '-' }}</td>
    <td>
      <input type="radio" name="release_group" value="{{ result['id'] }}">
    </td>
  </tr>

{% elif type=="event" %}
  <tr>
    <td>
      <a href="{{ url_for('event.entity', id=result.id) }}" target="_blank">{{ result['name'] }}</a>
      {% if result['disambiguation'] %}
        <span class="text-muted">({{ result['life-span']['begin'] }} - {{ result['life-span']['end'] }})</span>
      {% endif %}
    </td>
    <td>
      {% if result['artist-relation-list'] %}
        <a href="{{ url_for('artist.entity', id=result['artist-relation-list'][0].artist.id) }}" target="_blank">{{ result['artist-relation-list'][0]['artist']['name'] or '-' }}</a>
        {% set count = result['artist-relation-list'] | length %}
        {% if count > 1 %}
          + {{ count - 1 }} {{ _("more") }}
        {% endif %}
      {% else %}
        -
      {% endif %}
    </td>
    <td>
      {% if result['place-relation-list'] %}
        {{ result['place-relation-list'][0]['place']['name'] or '-' }}
      {% else %}
        -
      {% endif %}
    </td>
    <td>
      <input type="radio" name="event" value="{{ result['id'] }}">
    </td>
  </tr>

{% endif %}
{% endfor %}